/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegistraciyaRouteImport } from './routes/registraciya'
import { Route as RoditelRouteImport } from './routes/roditel'
import { Route as UchenikRouteImport } from './routes/uchenik'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as UrokTopicIdRouteImport } from './routes/urok.$topicId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraciyaRoute = RegistraciyaRouteImport.update({
  id: '/registraciya',
  path: '/registraciya',
  getParentRoute: () => rootRouteImport,
} as any)
const RoditelRoute = RoditelRouteImport.update({
  id: '/roditel',
  path: '/roditel',
  getParentRoute: () => rootRouteImport,
} as any)
const UchenikRoute = UchenikRouteImport.update({
  id: '/uchenik',
  path: '/uchenik',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const UrokTopicIdRoute = UrokTopicIdRouteImport.update({
  id: '/urok/$topicId',
  path: '/urok/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/registraciya': typeof RegistraciyaRoute
  '/roditel': typeof RoditelRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/registraciya': typeof RegistraciyaRoute
  '/roditel': typeof RoditelRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  '/admin': typeof AdminRoute
  '/registraciya': typeof RegistraciyaRoute
  '/roditel': typeof RoditelRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/robots.txt' | '/sitemap.xml' | '/admin' | '/registraciya' | '/roditel' | '/uchenik' | '/vhod' | '/urok/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/robots.txt' | '/sitemap.xml' | '/admin' | '/registraciya' | '/roditel' | '/uchenik' | '/vhod' | '/urok/$topicId'
  id: '__root__' | '/' | '/robots.txt' | '/sitemap.xml' | '/admin' | '/registraciya' | '/roditel' | '/uchenik' | '/vhod' | '/urok/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  RegistraciyaRoute: typeof RegistraciyaRoute
  RoditelRoute: typeof RoditelRoute
  UchenikRoute: typeof UchenikRoute
  VhodRoute: typeof VhodRoute
  UrokTopicIdRoute: typeof UrokTopicIdRoute
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registraciya': {
      id: '/registraciya'
      path: '/registraciya'
      fullPath: '/registraciya'
      preLoaderRoute: typeof RegistraciyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roditel': {
      id: '/roditel'
      path: '/roditel'
      fullPath: '/roditel'
      preLoaderRoute: typeof RoditelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uchenik': {
      id: '/uchenik'
      path: '/uchenik'
      fullPath: '/uchenik'
      preLoaderRoute: typeof UchenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urok/$topicId': {
      id: '/urok/$topicId'
      path: '/urok/$topicId'
      fullPath: '/urok/$topicId'
      preLoaderRoute: typeof UrokTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  RegistraciyaRoute: RegistraciyaRoute,
  RoditelRoute: RoditelRoute,
  UchenikRoute: UchenikRoute,
  VhodRoute: VhodRoute,
  UrokTopicIdRoute: UrokTopicIdRoute,
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
