/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VosstanovlenieRouteImport } from './routes/vosstanovlenie'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as UchenikRouteImport } from './routes/uchenik'
import { Route as TablicaUmnozheniyaRouteImport } from './routes/tablica-umnozheniya'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShulteRouteImport } from './routes/shulte'
import { Route as SchetRouteImport } from './routes/schet'
import { Route as RoditelRouteImport } from './routes/roditel'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistraciyaRouteImport } from './routes/registraciya'
import { Route as PriglashenieRouteImport } from './routes/priglashenie'
import { Route as PravopisanieRouteImport } from './routes/pravopisanie'
import { Route as PolitikaRouteImport } from './routes/politika'
import { Route as OplataRouteImport } from './routes/oplata'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as NovyyParolRouteImport } from './routes/novyy-parol'
import { Route as KtoRouteImport } from './routes/kto'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ChtenieRouteImport } from './routes/chtenie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepetitorIndexRouteImport } from './routes/repetitor.index'
import { Route as UrokTopicIdRouteImport } from './routes/urok.$topicId'
import { Route as RepetitorTrenazheryRouteImport } from './routes/repetitor.trenazhery'
import { Route as RepetitorTemyRouteImport } from './routes/repetitor.temy'
import { Route as RepetitorPodpiskaRouteImport } from './routes/repetitor.podpiska'
import { Route as RepetitorUchenikChildIdRouteImport } from './routes/repetitor.uchenik.$childId'

const VosstanovlenieRoute = VosstanovlenieRouteImport.update({
  id: '/vosstanovlenie',
  path: '/vosstanovlenie',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const UchenikRoute = UchenikRouteImport.update({
  id: '/uchenik',
  path: '/uchenik',
  getParentRoute: () => rootRouteImport,
} as any)
const TablicaUmnozheniyaRoute = TablicaUmnozheniyaRouteImport.update({
  id: '/tablica-umnozheniya',
  path: '/tablica-umnozheniya',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShulteRoute = ShulteRouteImport.update({
  id: '/shulte',
  path: '/shulte',
  getParentRoute: () => rootRouteImport,
} as any)
const SchetRoute = SchetRouteImport.update({
  id: '/schet',
  path: '/schet',
  getParentRoute: () => rootRouteImport,
} as any)
const RoditelRoute = RoditelRouteImport.update({
  id: '/roditel',
  path: '/roditel',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraciyaRoute = RegistraciyaRouteImport.update({
  id: '/registraciya',
  path: '/registraciya',
  getParentRoute: () => rootRouteImport,
} as any)
const PriglashenieRoute = PriglashenieRouteImport.update({
  id: '/priglashenie',
  path: '/priglashenie',
  getParentRoute: () => rootRouteImport,
} as any)
const PravopisanieRoute = PravopisanieRouteImport.update({
  id: '/pravopisanie',
  path: '/pravopisanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaRoute = PolitikaRouteImport.update({
  id: '/politika',
  path: '/politika',
  getParentRoute: () => rootRouteImport,
} as any)
const OplataRoute = OplataRouteImport.update({
  id: '/oplata',
  path: '/oplata',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const NovyyParolRoute = NovyyParolRouteImport.update({
  id: '/novyy-parol',
  path: '/novyy-parol',
  getParentRoute: () => rootRouteImport,
} as any)
const KtoRoute = KtoRouteImport.update({
  id: '/kto',
  path: '/kto',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChtenieRoute = ChtenieRouteImport.update({
  id: '/chtenie',
  path: '/chtenie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitorIndexRoute = RepetitorIndexRouteImport.update({
  id: '/repetitor/',
  path: '/repetitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrokTopicIdRoute = UrokTopicIdRouteImport.update({
  id: '/urok/$topicId',
  path: '/urok/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitorTrenazheryRoute = RepetitorTrenazheryRouteImport.update({
  id: '/repetitor/trenazhery',
  path: '/repetitor/trenazhery',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitorTemyRoute = RepetitorTemyRouteImport.update({
  id: '/repetitor/temy',
  path: '/repetitor/temy',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitorPodpiskaRoute = RepetitorPodpiskaRouteImport.update({
  id: '/repetitor/podpiska',
  path: '/repetitor/podpiska',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitorUchenikChildIdRoute = RepetitorUchenikChildIdRouteImport.update({
  id: '/repetitor/uchenik/$childId',
  path: '/repetitor/uchenik/$childId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chtenie': typeof ChtenieRoute
  '/demo': typeof DemoRoute
  '/kto': typeof KtoRoute
  '/novyy-parol': typeof NovyyParolRoute
  '/oferta': typeof OfertaRoute
  '/oplata': typeof OplataRoute
  '/politika': typeof PolitikaRoute
  '/pravopisanie': typeof PravopisanieRoute
  '/priglashenie': typeof PriglashenieRoute
  '/registraciya': typeof RegistraciyaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roditel': typeof RoditelRoute
  '/schet': typeof SchetRoute
  '/shulte': typeof ShulteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablica-umnozheniya': typeof TablicaUmnozheniyaRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/vosstanovlenie': typeof VosstanovlenieRoute
  '/repetitor/podpiska': typeof RepetitorPodpiskaRoute
  '/repetitor/temy': typeof RepetitorTemyRoute
  '/repetitor/trenazhery': typeof RepetitorTrenazheryRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  '/repetitor/': typeof RepetitorIndexRoute
  '/repetitor/uchenik/$childId': typeof RepetitorUchenikChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chtenie': typeof ChtenieRoute
  '/demo': typeof DemoRoute
  '/kto': typeof KtoRoute
  '/novyy-parol': typeof NovyyParolRoute
  '/oferta': typeof OfertaRoute
  '/oplata': typeof OplataRoute
  '/politika': typeof PolitikaRoute
  '/pravopisanie': typeof PravopisanieRoute
  '/priglashenie': typeof PriglashenieRoute
  '/registraciya': typeof RegistraciyaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roditel': typeof RoditelRoute
  '/schet': typeof SchetRoute
  '/shulte': typeof ShulteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablica-umnozheniya': typeof TablicaUmnozheniyaRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/vosstanovlenie': typeof VosstanovlenieRoute
  '/repetitor/podpiska': typeof RepetitorPodpiskaRoute
  '/repetitor/temy': typeof RepetitorTemyRoute
  '/repetitor/trenazhery': typeof RepetitorTrenazheryRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  '/repetitor': typeof RepetitorIndexRoute
  '/repetitor/uchenik/$childId': typeof RepetitorUchenikChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chtenie': typeof ChtenieRoute
  '/demo': typeof DemoRoute
  '/kto': typeof KtoRoute
  '/novyy-parol': typeof NovyyParolRoute
  '/oferta': typeof OfertaRoute
  '/oplata': typeof OplataRoute
  '/politika': typeof PolitikaRoute
  '/pravopisanie': typeof PravopisanieRoute
  '/priglashenie': typeof PriglashenieRoute
  '/registraciya': typeof RegistraciyaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roditel': typeof RoditelRoute
  '/schet': typeof SchetRoute
  '/shulte': typeof ShulteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablica-umnozheniya': typeof TablicaUmnozheniyaRoute
  '/uchenik': typeof UchenikRoute
  '/vhod': typeof VhodRoute
  '/vosstanovlenie': typeof VosstanovlenieRoute
  '/repetitor/podpiska': typeof RepetitorPodpiskaRoute
  '/repetitor/temy': typeof RepetitorTemyRoute
  '/repetitor/trenazhery': typeof RepetitorTrenazheryRoute
  '/urok/$topicId': typeof UrokTopicIdRoute
  '/repetitor/': typeof RepetitorIndexRoute
  '/repetitor/uchenik/$childId': typeof RepetitorUchenikChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chtenie'
    | '/demo'
    | '/kto'
    | '/novyy-parol'
    | '/oferta'
    | '/oplata'
    | '/politika'
    | '/pravopisanie'
    | '/priglashenie'
    | '/registraciya'
    | '/robots.txt'
    | '/roditel'
    | '/schet'
    | '/shulte'
    | '/sitemap.xml'
    | '/tablica-umnozheniya'
    | '/uchenik'
    | '/vhod'
    | '/vosstanovlenie'
    | '/repetitor/podpiska'
    | '/repetitor/temy'
    | '/repetitor/trenazhery'
    | '/urok/$topicId'
    | '/repetitor/'
    | '/repetitor/uchenik/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chtenie'
    | '/demo'
    | '/kto'
    | '/novyy-parol'
    | '/oferta'
    | '/oplata'
    | '/politika'
    | '/pravopisanie'
    | '/priglashenie'
    | '/registraciya'
    | '/robots.txt'
    | '/roditel'
    | '/schet'
    | '/shulte'
    | '/sitemap.xml'
    | '/tablica-umnozheniya'
    | '/uchenik'
    | '/vhod'
    | '/vosstanovlenie'
    | '/repetitor/podpiska'
    | '/repetitor/temy'
    | '/repetitor/trenazhery'
    | '/urok/$topicId'
    | '/repetitor'
    | '/repetitor/uchenik/$childId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chtenie'
    | '/demo'
    | '/kto'
    | '/novyy-parol'
    | '/oferta'
    | '/oplata'
    | '/politika'
    | '/pravopisanie'
    | '/priglashenie'
    | '/registraciya'
    | '/robots.txt'
    | '/roditel'
    | '/schet'
    | '/shulte'
    | '/sitemap.xml'
    | '/tablica-umnozheniya'
    | '/uchenik'
    | '/vhod'
    | '/vosstanovlenie'
    | '/repetitor/podpiska'
    | '/repetitor/temy'
    | '/repetitor/trenazhery'
    | '/urok/$topicId'
    | '/repetitor/'
    | '/repetitor/uchenik/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChtenieRoute: typeof ChtenieRoute
  DemoRoute: typeof DemoRoute
  KtoRoute: typeof KtoRoute
  NovyyParolRoute: typeof NovyyParolRoute
  OfertaRoute: typeof OfertaRoute
  OplataRoute: typeof OplataRoute
  PolitikaRoute: typeof PolitikaRoute
  PravopisanieRoute: typeof PravopisanieRoute
  PriglashenieRoute: typeof PriglashenieRoute
  RegistraciyaRoute: typeof RegistraciyaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RoditelRoute: typeof RoditelRoute
  SchetRoute: typeof SchetRoute
  ShulteRoute: typeof ShulteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TablicaUmnozheniyaRoute: typeof TablicaUmnozheniyaRoute
  UchenikRoute: typeof UchenikRoute
  VhodRoute: typeof VhodRoute
  VosstanovlenieRoute: typeof VosstanovlenieRoute
  RepetitorPodpiskaRoute: typeof RepetitorPodpiskaRoute
  RepetitorTemyRoute: typeof RepetitorTemyRoute
  RepetitorTrenazheryRoute: typeof RepetitorTrenazheryRoute
  UrokTopicIdRoute: typeof UrokTopicIdRoute
  RepetitorIndexRoute: typeof RepetitorIndexRoute
  RepetitorUchenikChildIdRoute: typeof RepetitorUchenikChildIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vosstanovlenie': {
      id: '/vosstanovlenie'
      path: '/vosstanovlenie'
      fullPath: '/vosstanovlenie'
      preLoaderRoute: typeof VosstanovlenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uchenik': {
      id: '/uchenik'
      path: '/uchenik'
      fullPath: '/uchenik'
      preLoaderRoute: typeof UchenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablica-umnozheniya': {
      id: '/tablica-umnozheniya'
      path: '/tablica-umnozheniya'
      fullPath: '/tablica-umnozheniya'
      preLoaderRoute: typeof TablicaUmnozheniyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shulte': {
      id: '/shulte'
      path: '/shulte'
      fullPath: '/shulte'
      preLoaderRoute: typeof ShulteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schet': {
      id: '/schet'
      path: '/schet'
      fullPath: '/schet'
      preLoaderRoute: typeof SchetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roditel': {
      id: '/roditel'
      path: '/roditel'
      fullPath: '/roditel'
      preLoaderRoute: typeof RoditelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registraciya': {
      id: '/registraciya'
      path: '/registraciya'
      fullPath: '/registraciya'
      preLoaderRoute: typeof RegistraciyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priglashenie': {
      id: '/priglashenie'
      path: '/priglashenie'
      fullPath: '/priglashenie'
      preLoaderRoute: typeof PriglashenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravopisanie': {
      id: '/pravopisanie'
      path: '/pravopisanie'
      fullPath: '/pravopisanie'
      preLoaderRoute: typeof PravopisanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika': {
      id: '/politika'
      path: '/politika'
      fullPath: '/politika'
      preLoaderRoute: typeof PolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oplata': {
      id: '/oplata'
      path: '/oplata'
      fullPath: '/oplata'
      preLoaderRoute: typeof OplataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novyy-parol': {
      id: '/novyy-parol'
      path: '/novyy-parol'
      fullPath: '/novyy-parol'
      preLoaderRoute: typeof NovyyParolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kto': {
      id: '/kto'
      path: '/kto'
      fullPath: '/kto'
      preLoaderRoute: typeof KtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chtenie': {
      id: '/chtenie'
      path: '/chtenie'
      fullPath: '/chtenie'
      preLoaderRoute: typeof ChtenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetitor/': {
      id: '/repetitor/'
      path: '/repetitor'
      fullPath: '/repetitor/'
      preLoaderRoute: typeof RepetitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urok/$topicId': {
      id: '/urok/$topicId'
      path: '/urok/$topicId'
      fullPath: '/urok/$topicId'
      preLoaderRoute: typeof UrokTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetitor/trenazhery': {
      id: '/repetitor/trenazhery'
      path: '/repetitor/trenazhery'
      fullPath: '/repetitor/trenazhery'
      preLoaderRoute: typeof RepetitorTrenazheryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetitor/temy': {
      id: '/repetitor/temy'
      path: '/repetitor/temy'
      fullPath: '/repetitor/temy'
      preLoaderRoute: typeof RepetitorTemyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetitor/podpiska': {
      id: '/repetitor/podpiska'
      path: '/repetitor/podpiska'
      fullPath: '/repetitor/podpiska'
      preLoaderRoute: typeof RepetitorPodpiskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetitor/uchenik/$childId': {
      id: '/repetitor/uchenik/$childId'
      path: '/repetitor/uchenik/$childId'
      fullPath: '/repetitor/uchenik/$childId'
      preLoaderRoute: typeof RepetitorUchenikChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChtenieRoute: ChtenieRoute,
  DemoRoute: DemoRoute,
  KtoRoute: KtoRoute,
  NovyyParolRoute: NovyyParolRoute,
  OfertaRoute: OfertaRoute,
  OplataRoute: OplataRoute,
  PolitikaRoute: PolitikaRoute,
  PravopisanieRoute: PravopisanieRoute,
  PriglashenieRoute: PriglashenieRoute,
  RegistraciyaRoute: RegistraciyaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RoditelRoute: RoditelRoute,
  SchetRoute: SchetRoute,
  ShulteRoute: ShulteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TablicaUmnozheniyaRoute: TablicaUmnozheniyaRoute,
  UchenikRoute: UchenikRoute,
  VhodRoute: VhodRoute,
  VosstanovlenieRoute: VosstanovlenieRoute,
  RepetitorPodpiskaRoute: RepetitorPodpiskaRoute,
  RepetitorTemyRoute: RepetitorTemyRoute,
  RepetitorTrenazheryRoute: RepetitorTrenazheryRoute,
  UrokTopicIdRoute: UrokTopicIdRoute,
  RepetitorIndexRoute: RepetitorIndexRoute,
  RepetitorUchenikChildIdRoute: RepetitorUchenikChildIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
